### ISSUE TITLE
Build error on jdk8 tests

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/bumblebench#36]
Found at https://github.com/adoptium/infrastructure/issues/3718 - log excerpt is in that issue
Likely caused by https://github.com/adoptium/bumblebench/pull/35 where the failing lines were added. Possible jdk8u specific issue with a construct that was added in later JDKs?
Noting that [job 666](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.perf_x86-64_windows/666/) was a re-run of the last successful build and also failed, therefore it is unrelated to the "special" build referenced in the infrastructure issue where this was seen.
FYI @dylanjtuttle

**Comment by maggietuttle** [comment]
Whoops, sorry! Looks like `String.repeat` is a JDK 11+ feature. I could use a for loop to do the repeating manually, would that be acceptable?

**Comment by sxa** [comment]
> Whoops, sorry! Looks like `String.repeat` is a JDK 11+ feature. I could use a for loop to do the repeating manually, would that be acceptable?

Sounds good to me if it lets the job run cleanly ;-)
